=== Haimanot1989/church/schemas/online_meeting.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["key", "slug", "order", "title"],
  "properties": {
    "key": {
      "type": "string",
      "description": "Original object key for backward compatibility"
    },
    "slug": {
      "type": "string",
      "description": "URL-friendly identifier"
    },
    "order": {
      "type": "number",
      "description": "Sort order"
    },
    "date": {
      "type": ["string", "null"],
      "description": "Meeting date (YYYY-MM-DD format)"
    },
    "title": {
      "type": "string",
      "description": "Meeting title"
    },
    "platformName": {
      "type": "string",
      "description": "Platform name (Zoom, Microsoft Teams, etc.)"
    },
    "imageUrl": {
      "type": "string",
      "description": "Meeting image or banner"
    },
    "zoomInfo": {
      "type": "object",
      "description": "Meeting platform details"
    },
    "importantMessage": {
      "type": "object",
      "description": "Important message or announcement"
    },
    "time": {
      "type": "array",
      "description": "Meeting schedule"
    },
    "contactInformation": {
      "type": "object",
      "description": "Contact details"
    }
  }
}

=== Haimanot1989/church/src/content/online-meetings/acifnayouthlordssupper.json
{
  "key": "ACIFNAYouthLordsSupper",
  "slug": "acifnayouthlordssupper",
  "order": 9,
  "date": null,
  "platformName": "Zoom",
  "zoomInfo": {
    "language": "",
    "meetingId": "6477022625",
    "meetingPassword": "2625",
    "meetingLink": {
      "map": "https://us02web.zoom.us/j/F6477022625?pwd=bjVYMDh2ZUQwNTZzd1F0VVdmNldPZz09",
      "placeName": "Join the meeting by clicking on this link or using the details above in the zoom app"
    }
  },
  "imageUrl": "./acimaca_2021.png",
  "title": "ACIMCA 2021 - Virtual Youth Conference",
  "time": [
    {
      "id": 1,
      "date": {
        "day": "Friday",
        "date": "2",
        "sup": "nd",
        "month": "April"
      },
      "startTime": "17:00 CEST",
      "finishTime": " "
    },
    {
      "id": 1,
      "date": {
        "day": "Saturday",
        "date": "3",
        "sup": "rd",
        "month": "April"
      },
      "startTime": "16:00 CEST",
      "finishTime": " "
    },
    {
      "id": 1,
      "date": {
        "day": "Sunday",
        "date": "4",
        "sup": "th",
        "month": "April"
      },
      "startTime": "17:00 CEST",
      "finishTime": " "
    }
  ]
}

=== Haimanot1989/church/src/content/online-meetings/acifnayouth.json
{
  "key": "ACIFNAYouth",
  "slug": "acifnayouth",
  "order": 3,
  "date": null,
  "platformName": "Zoom",
  "zoomInfo": {
    "language": "",
    "meetingId": "848 2692 3348",
    "meetingPassword": "acts02:38",
    "meetingLink": {
      "map": "https://us02web.zoom.us/j/84826923348?pwd=VmZHbzlpRGhLUXVNVXdyYm9BVThVUT09",
      "placeName": "Join the meeting by clicking on this link or using the meeting id above in the zoom app"
    }
  },
  "imageUrl": "./acifna_youth_thanksgiving.png",
  "title": "Digital ACIFNA Annual Youth Thanksgiving Conference",
  "time": [
    {
      "id": 1,
      "date": {
        "day": "Part 1 - Sunday",
        "date": "3",
        "sup": "rd",
        "month": "January"
      },
      "startTime": "16:00 CET",
      "finishTime": "20:00 CET"
    },
    {
      "id": 2,
      "date": {
        "day": "Part 2 - Sunday",
        "date": "3",
        "sup": "rd",
        "month": "January"
      },
      "startTime": "21:30 CET",
      "finishTime": "24:00 CET"
    }
  ]
}

=== Haimanot1989/church/src/content/online-meetings/saturdaybiblestudyonzoom.json
{
  "key": "saturdayBibleStudyOnZoom",
  "slug": "saturdaybiblestudyonzoom",
  "order": 5,
  "date": null,
  "zoomInfo": {
    "meetingId": "639 807 0890",
    "meetingPassword": "OneGod",
    "meetingLink": {
      "map": "https://us02web.zoom.us/j/6398070890?pwd=MlZxZWcwR3I0d3R1MmhDN0syaUx0Zz09",
      "placeName": "Join the meeting by click on this link or use the id and password above in the zoom app"
    }
  },
  "imageUrl": "./bible-study.png",
  "title": "Online Bible study on holiness",
  "time": [
    {
      "id": 1,
      "date": {
        "day": "Saturday",
        "date": "23",
        "sup": "rd",
        "month": "May"
      },
      "startTime": "16:00 CEST",
      "finishTime": "19:00 CEST"
    }
  ],
  "contactInformation": {
    "emails": [
      "frezer26@gmail.com"
    ],
    "phoneNumbers": [
      "+16 13 816 74 41"
    ]
  }
}
